### ISSUE TITLE
Colors design tokens

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#1]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Core theme (Light mode)

### Summary 💡

Improve our color naming convention. 
Rework our foundation to get ready for design token. 

### Examples 🌈

[Material Design 2](https://material.io/design/color/the-color-system.html#color-usage-and-palettes)
[Material Design 3](https://m3.material.io/styles/color/overview)
[Atlassian Design](https://atlassian.design/foundations/color)

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
This topic has been launched in beta test.
However, its status in the board no longer reflects the current reality, so it has been moved to our "New" column.
We will keep you informed of the different advances.
Thank you.
