### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#10]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A way of informing the user of important changes in a prominent way. With different status/degree of importance.

### Examples 🌈

[Banner component](https://www.figma.com/file/BiWHJTZHHTLk0QBhDuFhbS/DR---Workshop?node-id=16%3A3).
[Alert gallery
](https://component.gallery/components/alert/)

![image](https://user-images.githubusercontent.com/65814825/178747835-40da9b47-86ab-4575-a5ca-2f4c8543195b.png)
![image](https://user-images.githubusercontent.com/65814825/178747888-49898ef6-7f73-4f46-8ed1-ab4e792fd6fe.png)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Will be tracked here: https://github.com/dktunited/vitamin-play/issues/43
