### ISSUE TITLE
Add a small size for Quantity component

### ISSUE THREAD

**Issue by dsumac** [Decathlon/vitamin-design#101]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

[The quantity component](https://www.decathlon.design/726f8c765/p/207abd-quantity/b/20e6b4) seems to have only one size for rendering.

Is it possible to have a more smaller size ? Do we want 1/2/3 possible sizes ?

### Motivation 🔦

In our context we have already a specifical layout with a custom component like "vitamine quantity". In order to migrate this component to Vitamine we want to use it. But the actual/default size is too big.    

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [x] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1360
```

**Comment by Sabrinavigil** [comment]
Hi @dsumac thanks for your issue. To groom your ticket, could you give us some context ? Do you have a Screen ? 
What size will meet your needs?

**Comment by dsumac** [comment]
We'll give you more information with capture as soon as possible (check with Morgan the UI on the concerned project)

**Comment by dsumac** [comment]
### Example

As you can see, we have a custom "quantity" component and on the other line the "quantity vitamine" component.

<img width="1037" alt="Capture d’écran 2022-10-14 à 10 20 51" src="https://user-images.githubusercontent.com/6465113/195799258-6f44f6d5-e967-4708-979d-aaf70a163fd7.png">

### Proposal

- Vitamine Quantity component with a smaller "size"
- do you have an other proposal ? rework the table design ...

**Comment by MARIEDELATTRE** [comment]
Doing.
Just note that for medium size the icon size has to change from 20 to 24 because we have changed that on our icon alone buttons recently so I also fix that.
