### ISSUE TITLE
[Icon]: New icon <rocket>

### ISSUE THREAD

**Issue by ablareau** [Decathlon/vitamin-design#102]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

rocket

### Icon description

Cette icône serait utilisée pour accéder à l'outil Beamer (outil qui est présent sur tous les produits de la BU Création). Elle serait accessible dans les header.

J'ai simplement repris l'icône "rocket-2" de remixicon et j'ai rajouté une rotation de -45° pour bien la différencier de l'icône Notification.
![rocket](https://user-images.githubusercontent.com/116070030/196389924-6de744d0-076f-4274-98e2-78a99ae2a0a9.svg)

**Comment by Sabrinavigil** [comment]
Thanks for your contribution, it's under review ;)

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1284)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
