### ISSUE TITLE
Add a new icon <tools>

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#103]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

Tools

### Icon description

Used o represent the repair category into sustainable development
<img width="70" alt="Capture d’écran 2022-10-05 à 16 38 13" src="https://user-images.githubusercontent.com/100569235/196944498-a714ca5d-9ef5-4fa1-a0d9-60e7a05b2112.png">

### Icon keywords

tool, tools, repair

### Icon SVG code

```shell
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M5.33 3.271a3.5 3.5 0 0 1 4.254 4.963l10.709 10.71-1.414 1.414-10.71-10.71a3.502 3.502 0 0 1-4.962-4.255L5.444 7.63a1.5 1.5 0 1 0 2.121-2.121L5.329 3.27zm10.367 1.884l3.182-1.768 1.414 1.414-1.768 3.182-1.768.354-2.12 2.121-1.415-1.414 2.121-2.121.354-1.768zm-6.718 8.132l1.414 1.414-5.303 5.303a1 1 0 0 1-1.492-1.327l.078-.087 5.303-5.303z"/></svg>
```

**Comment by Sabrinavigil** [comment]
Thanks @felixbusadkt we add it :)

**Comment by lauthieb** [comment]
Thanks @felixbusadkt & @Sabrinavigil 

Here are the links for the development follow-up:
- https://github.com/Decathlon/vitamin-web/issues/1301
- https://github.com/Decathlon/vitamin-android/issues/142
- https://github.com/Decathlon/vitamin-ios/issues/96
