### ISSUE TITLE
Mismatch between the documentation and the Android/iOS figma libraries for some Button component variants

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-design#104]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

We have this illustration for Android & iOS Button component:

![CleanShot 2022-10-20 at 14 17 21](https://user-images.githubusercontent.com/9600228/196946497-cedfd936-241c-482d-a5d0-767ef76042ab.png)

But when we check inside Figma libraries, there is a mismatch for some Button component variants:

![CleanShot 2022-10-20 at 14 17 52](https://user-images.githubusercontent.com/9600228/196946667-7db5a9e3-06e1-4dfb-a123-91b74a067f20.png)
![CleanShot 2022-10-20 at 14 17 46](https://user-images.githubusercontent.com/9600228/196946663-b3c9b8ff-8aab-4d2e-bd2c-77772df362da.png)

### Expected behavior 🤔

We need to match documentation & design/dev

### Context 🔦

Pierre Fournier & @florentlotthepro want to use the new tertiary button variant.
Thanks for reporting this.

**Comment by MARIEDELATTRE** [comment]
There is no missing variants on our library, the image is wrong because the 2 last buttons should be called "primary reversed" and "ghost reversed"
