### ISSUE TITLE
Possibility to add an optional label at the right of the accordion summary for the accordion component

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-design#106]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

We could be able to adds an optional label on the right of the accordion when it is closed. It would be aligned with the summary, but would have a smaller font. Possibility to add also extra styles to it.

### Dependencies 📦

No dependencies

### Examples 🌈

![image](https://user-images.githubusercontent.com/97453800/197800802-7cb96f2c-3ced-4fe0-afd8-62c830983392.png)

### Motivation 🔦

This feature could help the user to see some information before opening the accordion, saving a click if he is not interested in opening the accordion.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Thanks, we add this variation to the parent accordion ticket
