### ISSUE TITLE
Dropdown component in Figma doesn't contain any scroll bar while documentation is showing one

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#107]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

The dropdown in Figma doesn't contain any scrollbar
<img width="472" alt="Capture d’écran 2022-10-26 à 17 27 22" src="https://user-images.githubusercontent.com/61324309/198068733-efe89394-c066-4a58-88a7-ed85ffe754d9.png">

Whereas there is one on documentation
<img width="843" alt="Capture d’écran 2022-10-26 à 17 27 50" src="https://user-images.githubusercontent.com/61324309/198068903-7f25b68c-fcd3-4267-8e32-05b7a9406c51.png">

### Expected behavior 🤔

See what happen on dev side (if the scrollbar is custom or not) and decide what to do on the basis of this.

**Comment by Sabrinavigil** [comment]
Remove the "scroll bar" in the documentation
Take a look at the asset, do we add scroll bar like keyboard ?

**Comment by MARIEDELATTRE** [comment]
removed from documentation ✅

**Comment by Sabrinavigil** [comment]
Reviewed ✅

**Comment by Sabrinavigil** [comment]
No impact dev
