### ISSUE TITLE
Document how to use the “Phrase” Plugin 

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#108]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Prase is a validated tool 

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Todo : get in touch with the Phrase PM to add Figma in the documentation

**Comment by SimonLeclercq** [comment]
Meet Up Schedule with Phrase PM, more info to come

**Comment by SimonLeclercq** [comment]
Documentation add, under review 👍

**Comment by MARIEDELATTRE** [comment]
Reviewed @SimonLeclercq. Need to be published.

**Comment by lauthieb** [comment]
Thanks @Sabrinavigil, @SimonLeclercq & @MARIEDELATTRE 🔥
