### ISSUE TITLE
Icon size in Quantity component is not correct

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#109]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Current behavior 😯

The icon size in quantity is 20px currently but we have changed icon size in icone alone button variants.
So we need tu change the icone in quantity from 20px to 24px (already done on web in ticket #101)

**Comment by lauthieb** [comment]
Thanks @MARIEDELATTRE, this will be brought in these issues:
- https://github.com/Decathlon/vitamin-android/issues/93
- https://github.com/Decathlon/vitamin-compose/issues/7
