### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#11]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Contact @alexandre.marquesdasilva

### Examples 🌈

![image](https://user-images.githubusercontent.com/65814825/178751620-00877296-57dd-4433-ae98-914787b8f36a.png)
https://ant.design/components/carousel/
https://developer.apple.com/design/human-interface-guidelines/components/presentation/page-controls/
https://www.figma.com/community/file/1047907758163889748

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Will be tracked here: https://github.com/dktunited/vitamin-play/issues/47
