### ISSUE TITLE
Drop price variation for price component

### ISSUE THREAD

**Issue by manglard** [Decathlon/vitamin-design#113]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

Drop price should communicate to clients that DKT has reduce the price of the product.
The current behavior is the following :
![Capture d’écran 2022-11-02 à 16 31 16](https://user-images.githubusercontent.com/107057726/199538447-bd8daf1d-81c8-41d2-a89b-5cad6849a0da.png)
 

### Motivation 🔦

For now we have a regression to fix with the old design and we took the opportunity to had this variation to the Vitamin Component

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

**Comment by Sabrinavigil** [comment]
Thanks for the issue @manglard  :)

**Comment by MARIEDELATTRE** [comment]
We have added a documentation for price drop on decathlon.design (will be published in the next release)
<img width="436" alt="Capture d’écran 2023-01-06 à 12 28 16" src="https://user-images.githubusercontent.com/61324309/211004023-65abc803-dc6b-401e-98e4-ca7120ac3819.png">
