### ISSUE TITLE
Add Ditto to the allowlist

### ISSUE THREAD

**Issue by TimotheeBar** [Decathlon/vitamin-design#117]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin name

Ditto

### Figma plugin URL

https://www.figma.com/community/plugin/798826066406007173/%E2%9C%8D%EF%B8%8F-Ditto-%7C-collaborate-on-copy

### Why do you need this Figma plugin?

Test ux copy tool

**Comment by lauthieb** [comment]
Hi @TimotheeBar,

Thanks again for this new proposal.
Unfortunately my answer will be the same as https://github.com/Decathlon/vitamin-design/issues/118: 

>  Unfortunately we can't accept this plugin for now as Frontitude is not open source and linked to a pricing plan / terms of services / privacy policy, etc. that will need to be contracted with Decathlon officially. So, I close your issue, feel free to reach us if Decathlon has an official contract with Frontitude and we will check this together. 

I wish you a great day, 
Laurent
