### ISSUE TITLE
Add Frontitude to the allowlist

### ISSUE THREAD

**Issue by TimotheeBar** [Decathlon/vitamin-design#118]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin name

Frontitude

### Figma plugin URL

https://www.figma.com/community/plugin/809843676692807511/Frontitude-%E2%80%A2-UX-copy-management

### Why do you need this Figma plugin?

Test ux writting tools

**Comment by lauthieb** [comment]
Hi @TimotheeBar,
Thanks for your proposal.
Unfortunately we can't accept this plugin for now as Frontitude is not open source and linked to a pricing plan / terms of services / privacy policy, etc. that will need to be contracted with Decathlon officially.
So, I close your issue, feel free to reach us if Decathlon has an official contract with Frontitude and we will check this together.
I wish you a great day,
Laurent

**Comment by TimotheeBar** [comment]
Hi, I disagree with you, my whole point is to be able to test it with a free plan in order to see of we are going to integrate it in our design process.

**Comment by lauthieb** [comment]
@TimotheeBar, just sent you a Slack message to continue this discussion with @Sabrinavigil also :)
