### ISSUE TITLE
Add a new icon : tablet

### ISSUE THREAD

**Issue by Louis2411** [Decathlon/vitamin-design#119]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Icon or Asset name

tabet

### Icon or Asset description

We need to have the tablet icon available in addition to the desktop and mobile icon already present.
Action: Used to change Decathlon preview website to Desktop - Tablet - Mobile on NEMO (Decathlon New E-Merch Operator for Webmarketer).

The remix library version matches perfectly.

### Icon or Assets keywords

tablet

### Icon or Asset author

https://remixicon.com/

### Icon or Asset SVG code

```shell
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M6 4v16h12V4H6zM5 2h14a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1zm7 15a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/></svg>
```

### Are there any other important details?

Request by Louis Bronstein - Product Designer on NEMO

**Comment by Sabrinavigil** [comment]
Thanks for your contribution !

**Comment by MARIEDELATTRE** [comment]
Icon published on Figma (in dev libraries to come)

**Comment by Louis2411** [comment]
Thx a lot
