### ISSUE TITLE
Wrong icon naming

### ISSUE THREAD

**Issue by charlottemougenot** [Decathlon/vitamin-design#120]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Icons

### Current behavior 😯

Fill and line version are both named -line for :
- kakao-talk
- line

### Expected behavior 🤔

Filled version are named : 

- kakao-talk-fill
- line-fill

### Context 🔦

Can't export icons for libraries correctly with this naming error

### Screenshots / Videos 📸

<img width="602" alt="Capture d’écran 2022-11-14 à 17 12 34" src="https://user-images.githubusercontent.com/54030002/201709488-46a24e7e-2b10-46b1-a9d1-1868eb260e08.png">

**Comment by ManonPolle** [comment]
✅ Already named 
`vtmn_kakao_talk_line` & `vtmn_kakao_talk_fill`
`vtmn_line_fill` & `vtmn_line_line` 
in Android lib

**Comment by lauthieb** [comment]
OK for web ✅ 
https://github.com/Decathlon/vitamin-web/pull/1323

**Comment by lauthieb** [comment]
OK for iOS, just checked on their repo. I close it :)
