### ISSUE TITLE
Add icon on the label in Forms

### ISSUE THREAD

**Issue by Louis2411** [Decathlon/vitamin-design#121]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

The forms on vitamin are very great but we need new feature for use it on NEMO (New E-Merch Operator) project.
Need a little icon (16 or 18px) of the right of the label on all Forms (input, text area, select).
It's for add a (i) icon; for add more information of the content to apply on the form (very important on NEMO).

### Dependencies 📦

Forms on Vitamin.

### Examples 🌈

Vitamix icon 16x16 or 18x18 in the right on label with 8px of padding.

Exemple link :
https://www.figma.com/file/pYPxejpMUjYaczawkDMIvZ/Nemo_Maquettes?node-id=6076%3A148156&t=28tPmeFPTFxsWUUw-1

### Motivation 🔦

We can't use Vitamin Forms without this feature.

Request by Louis Bronstein - Product Designer on NEMO

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Thank you @Louis2411 for your request, your ticket will be groom next week :) 
We will keep you informed :)

**Comment by Sabrinavigil** [comment]
Validaded in grooming ! Need to define the solution (16x16 button is too small :) )

**Comment by Louis2411** [comment]
Thx, great !

**Comment by MARIEDELATTRE** [comment]
Hi @Louis2411, we've made a test on Figma libraries and to have a sufficient touch area we need to use an icon alone button.
The behaviour: hover of input and hover of icon button are triggered at the same time because they are not separated in the design construction actually. So it will be breaking change for us.



In conclusion, I'll add your request in the future major release of this component.

**Comment by Louis2411** [comment]
Ok, bad news for us. 
Thanks anyway

**Comment by lauthieb** [comment]
This issue had well been referenced in the different issues for input/textarea & select components for our next major release:
- https://github.com/Decathlon/vitamin-design/issues/61#issuecomment-1372366648
- https://github.com/Decathlon/vitamin-design/issues/60#issuecomment-1375669071

So we can close it as it's now referenced there.

Thanks again @Louis2411 for your request & understanding, you will be informed in these issues.

**Comment by Louis2411** [comment]
OK
