### ISSUE TITLE
Checkbox component constraints

### ISSUE THREAD

**Issue by jordivivesDKT** [Decathlon/vitamin-design#122]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

We’re having constraints trouble with the disabled state in the checkbox component because it has a fixed width. So when we try to change its container shape the checkbox doesn't behave as it should.

### Expected behavior 🤔

We expect the checkbox not to change its ratio shape when we change the text content.

### Context 🔦

We wanted to change the text next to the checkbox but when we did that the checkbox ratio broke on disabled state.

### Screenshots / Videos 📸

https://user-images.githubusercontent.com/94625843/202228375-146f24a8-7c12-4fc1-b10e-20a8bc0dd545.mov

**Comment by jordivivesDKT** [comment]
After a chat with Marie Delatre we saw we could do this fix from Spain in a branch and send the review afterwards.

**Comment by Sabrinavigil** [comment]
Amazing, I'll take a look this afternoon, thank you so much @jordivivesDKT :)

**Comment by MARIEDELATTRE** [comment]
Reviewed merged and published thanks a lot @jordivivesDKT
