### ISSUE TITLE
Add a new <run>

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#123]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Icon or Asset name

Run

### Icon or Asset description

Run is an icon with a person running. It represent sport.

[RemixIcon_SVG_2211211731.zip](https://github.com/Decathlon/vitamin-design/files/10058293/RemixIcon_SVG_2211211731.zip)

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
Great thanks @MARIEDELATTRE

**Comment by MARIEDELATTRE** [comment]
Icon published on Figma (in dev libraries to come)
