### ISSUE TITLE
Wrong spacing in the searchView

### ISSUE THREAD

**Issue by MaximeJineMaraval** [Decathlon/vitamin-design#124]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Current behavior 😯

In the Android search component, the spacing between the left back arrow and the search textField is equal to 12px.
![Capture d’écran 2022-11-23 à 16 55 46](https://user-images.githubusercontent.com/46402524/203591762-b1bbd219-badd-4f1d-8aef-db20e5988b31.png)

### Expected behavior 🤔

According to the material documentation (validated with @SimonLeclercq ), this spacing should be 32px, like in the topAppBar.

![Capture d’écran 2022-11-23 à 16 56 24](https://user-images.githubusercontent.com/46402524/203591820-4c2f318f-dc09-420b-8cc5-3acddfb4b569.png)
![Capture d’écran 2022-11-23 à 16 55 59](https://user-images.githubusercontent.com/46402524/203591830-491e584c-18e5-4953-a8ec-4734fd9e5341.png)

### Context 🔦

The modification is already applied in the Android XML library. Should be checked in the Android Compose library.

**Comment by Sabrinavigil** [comment]
Thanks for creating the issue, I had this ressource ;) 
https://m2.material.io/design/navigation/search.html#expandable-search
