### ISSUE TITLE
Search component without magnify button

### ISSUE THREAD

**Issue by jordivivesDKT** [Decathlon/vitamin-design#125]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

After a discussion with Sabrina Virgil we found it could be really helpful in some scenarios to have a new variation of the search component. A search similar to the native one on [Android](https://www.decathlon.design/726f8c765/p/666649-search/b/59ef13) and [IOS](https://www.decathlon.design/726f8c765/p/666649-search/b/756415) with a 🔍 search icon on the left to indicate that it's a search bar, but not as a button to validate.

### Dependencies 📦

Non detected.

### Examples 🌈

We can use as an example many other PC search fields in other retailers checkout such as (https://www.sprintersports.com/checkout) and many others.

### Motivation 🔦

As can be seen in the attached videos, nowadays, we are using the [vtmn Search](https://www.decathlon.design/726f8c765/p/666649-search/b/061ede) component as an input for the pickup point field in our funnel checkout on the NFS core version. As its nature is documented, this component has a 🔍 button on the right side to load the expected results when clicked but in this scenario, seems to be "useless". In this particular flow, we want the user to focus on the autocomplete suggestions, not use the button. Clicking the 🔍 here will result in nothing happening instead of loading a result page because the results are shown as a suggestion list. All this may produce frustration for our users or could induce an error during a critical part of our journey.

https://user-images.githubusercontent.com/94625843/203734190-75832661-9547-4b38-955d-883f64a2c5b8.mov

https://user-images.githubusercontent.com/94625843/203734208-fda9c990-3a68-4c4e-841e-bb1b8b470adf.mp4

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [x] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1358
```

**Comment by Sabrinavigil** [comment]
Thank you very much @jordivivesDKT for creating the issue :)

**Comment by MARIEDELATTRE** [comment]
A branch is currently under review to have a bolean (true/fasle) for search button in Figma.

![Image](https://user-images.githubusercontent.com/61324309/211033993-8bfb224f-16c8-464a-a526-b1a9b463ab69.png)

And I've added a note on our documentation see below:

![Image](https://user-images.githubusercontent.com/61324309/211033748-5d4f0491-c0fc-4128-b2d0-1569806f1b1b.png)

**Comment by lauthieb** [comment]
Hello,
fyi @Sabrinavigil @MARIEDELATTRE @SimonLeclercq @thibault-mahe @ManonPolle I just deleted the "components" label because I think we need to keep it for our new components (also for design tokens label).
Feel free to tell me if you think that's not ok.
Thank you!
