### ISSUE TITLE
Tooltip's Top right variant issue

### ISSUE THREAD

**Issue by Francois-Duchosal** [Decathlon/vitamin-design#126]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

When we tape text inside a Tooltip's Top right variant , the arrow is moving from the left to the right.

### Expected behavior 🤔

The arrow should stick on the left and not move at all.

### Screenshots / Videos 📸

![Capture d’écran 2022-11-24 à 17 17 14](https://user-images.githubusercontent.com/118997439/203829199-b41097df-efdc-4ad8-8eba-3af17a0065e0.png)

![Capture d’écran 2022-11-24 à 17 17 41](https://user-images.githubusercontent.com/118997439/203829277-a83e79ad-510a-4c74-9bc5-81f96f9a4af3.png)

**Comment by Sabrinavigil** [comment]
Thanks, François, we take a look 👀
