### ISSUE TITLE
Add html.to.design to the allowlist

### ISSUE THREAD

**Issue by RomThib** [Decathlon/vitamin-design#127]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin name

html.to.design

### Figma plugin URL

https://www.figma.com/community/plugin/1159123024924461424/html.to.design

### Why do you need this Figma plugin?

Reviews team (business unit: Decathlon Core Platform) is working on the redesign of its Legacy.
In this context, the internal tool _Openvoice_ is constantly being improved.
To speed up the creation of mockups, the Product team wants to use the html.to.design plugin to quickly create mockups from external benchmarks.

**Comment by lauthieb** [comment]
Hi @RomThib, thanks for your proposal.
Just accepted your request, you can now use html.to.design inside our Figma organization.
Have a nice day,
Laurent
