### ISSUE TITLE
Fixed FAB width

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#128]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Summary 💡

This button need to have width fixed to take the full Android page.

### Examples 🌈

https://lh3.googleusercontent.com/2nFCGSEZWHpjple3MqB9v3fFcyHNt69hCRCgT6dUTIibJjTOzVRj-dtI57xVw43ND-F0HMuCLrFSwqogDSvUsQ7oWdDoMW7xX-zAbA=w1064-v0

### Motivation 🔦

We use this component for sticky button inside filter page for instance and we need a variant with full width.

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [x] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-android/issues/154
- [ ] https://github.com/Decathlon/vitamin-compose/issues/69
```

**Comment by Sabrinavigil** [comment]
Thanks Felix !

**Comment by SimonLeclercq** [comment]
@Sabrinavigil @MARIEDELATTRE ok to make it appear in the documentation + code without changing design libraries ?

**Comment by SimonLeclercq** [comment]
@ManonPolle documentation updated. FAB on the design side already allows `full-with`. I let you look on your side to make the behavior possible on Android 🤖
