### ISSUE TITLE
Bug text input helper text web

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#13]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

On text input the helper text “saute” when we change state from default to hover

**Comment by Sabrinavigil** [comment]
is it dev or design ?

**Comment by thibault-mahe** [comment]
Seems ok in the storybook: https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-forms-text-input--overview 

Do you any link / app where we could check this behaviour and/or reproduce it please?
