### ISSUE TITLE
Add a new <republishing> icon

### ISSUE THREAD

**Issue by ablareau** [Decathlon/vitamin-design#130]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Icon or Asset name

Republishing

### Icon or Asset description

This icon shows a modification on a data or an input field, for a model card.
![republishing](https://user-images.githubusercontent.com/116070030/206155373-ac42ae42-55aa-4a2b-a12b-a78444d0ce6a.svg)

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
Hi @ablareau thanks for your contribution, we add it as soon as possible :)

**Comment by ablareau** [comment]
Hi @MARIEDELATTRE, 

Thank you for your response! The refresh icon is perfect so I don't need anymore the republishing icon :)
