### ISSUE TITLE
Figma files are in 404 (because not open to everyone) on the Theming documentation

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-design#133]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

https://www.decathlon.design/726f8c765/p/88a9a6-theming/b/354a0f

This page is not open (tested in private nagivation). So, people that aren't in Decathlon's Figma organization cannot see it.

### Expected behavior 🤔

Could be nice to see it :) 

Thanks!

### Screenshots / Videos 📸

<img width="1382" alt="CleanShot 2022-12-12 at 20 32 27@2x" src="https://user-images.githubusercontent.com/9600228/207137343-6839924d-a453-4973-a542-f712594f15d4.png">

**Comment by Sabrinavigil** [comment]
Done :)

**Comment by lauthieb** [comment]
Just added this for the next release of our doc: ![image](https://user-images.githubusercontent.com/9600228/210966799-94abfae8-076c-43aa-bbda-47879ffdbe8e.png)
