### ISSUE TITLE
Add a new sparkle icon

### ISSUE THREAD

**Issue by anttonuriarte** [Decathlon/vitamin-design#134]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Icon or Asset name

Sparkles

### Icon or Asset description

We use this icon to represent that a product needs to be clean when bringing it back for SecondeVie/Occasion.
It could be used as well to declare a "New Product" state.

### Icon or Assets keywords

Sparkles, Clean, Cleaning, Shiny, New, Bright

### Icon or Asset author

Antton Uriarte

### Icon or Asset SVG code

```shell
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.66669 14.1573L4.50336 9.83L0.176025 7.66667L4.50336 5.50333L6.66669 1.176L8.83003 5.50333L13.1574 7.66667L8.83003 9.83L6.66669 14.1573ZM3.15736 7.66667L5.49669 8.83667L6.66669 11.176L7.83669 8.83667L10.176 7.66667L7.83669 6.49667L6.66669 4.15733L5.49669 6.49667L3.15736 7.66667ZM12 14L13 16L14 14L16 13L14 12L13 10L12 12L10 13L12 14ZM12.8887 3.11133L13.6667 4.66667L14.4447 3.11133L16 2.33333L14.4447 1.55533L13.6667 0L12.8887 1.55533L11.3334 2.33333L12.8887 3.11133Z" fill="#001018"/>
</svg>
```

**Comment by MARIEDELATTRE** [comment]
@anttonuriarte Could you send me here your design file for this icon?

**Comment by MARIEDELATTRE** [comment]
Icon published on Figma (in dev libraries to come) @anttonuriarte
