### ISSUE TITLE
Problem with hover on Accordion component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#14]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

Hello, there is a problem with the accordion hover on the web UI Kit: a gray appears before the blue, which makes interactions and tests not very qualitative.

Contact @benjamin.hayez

**Comment by lauthieb** [comment]
@Sabrinavigil I close this issue as you just make it as "done" :). Feel free to reopen if I'm wrong! Thanks.

<img width="339" alt="CleanShot 2022-10-27 at 23 28 47@2x" src="https://user-images.githubusercontent.com/9600228/198401795-b7deb612-1fee-4e64-8656-3ec8b7c16e07.png">
