### ISSUE TITLE
Improve/Update Navbar Image

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-design#142]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Summary 💡

For now, there is a section in the documentation of the Navbar on Android that states that it is possible to add a background image on the Navbar : 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/26525340/208150391-acf88099-50e1-4d53-be5a-77749c2bbe58.png">

[Doc Decathlon Design](https://www.decathlon.design/726f8c765/p/165aa1-bar/b/56fd2b/t/552111)

For accessibility purposes, it may be important to change this doc, whether to raise awareness of accessibility issues that could bring this or simply remove this possibility to avoid contrast problems. (Or add a disclaimer to explain the possible problems with the image)

### Dependencies 📦

None

### Motivation 🔦

Make our interfaces the most accessible possible ;) 

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
Add a transparent top app bar

**Comment by lauthieb** [comment]
> Add a transparent top app bar

@SimonLeclercq needs to check regarding accessibility standards (because not in Material).

**Comment by Sabrinavigil** [comment]
with button background

![Image](https://user-images.githubusercontent.com/65814825/213407989-67ef3772-5441-4e31-b451-f2eabf81e17e.jpeg)
