### ISSUE TITLE
Documentation and presentation of text styles need to be clearer

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#144]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

- The documentation of text styles don't explain how to use text styles with html balises.
- Also there is no clear documentation on accesssibility and SEO recommendations.
- On the inspect mode of text styles, they are applied on `<p>` balises.

### Expected behavior 🤔

- We should document more text styles usages especially for accessiblity and SEO.
- We should change our storybook code demo with `<h2>` balises instead of `<p>` balises.

**Comment by SimonLeclercq** [comment]
" text styles are not correlated with semantics.

They are there to facilitate a hierarchy between styles.

You don't have to use a title 2 with an html 5 tag <h2></h2>"

**Comment by SimonLeclercq** [comment]
Message added to documentation, under review

**Comment by MARIEDELATTRE** [comment]
Reviewed good for me
