### ISSUE TITLE
Mismatch between design and development on organizm components (cards & lists) on mobile iOS and android

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#146]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

- On android they decided to just give the container of the card while on development side we have differents variants.
So it's more restricted on the design side. (

- Moreover on some variants there are differences between the platforms like on side image variants :
<img width="571" alt="Capture d’écran 2022-12-22 à 11 25 44" src="https://user-images.githubusercontent.com/61324309/209117441-3fe000f4-6905-444c-a32f-fb6f41a0d144.png">

### Expected behavior 🤔

We should be ISO dev<>design.
The card can be hard to use on the figma side, whereas if in mobile development it's hyper permissive it's not fair!

We need to decide and discuss @Sabrinavigil and @SimonLeclercq.

I propose to add a container variant on the 3 platforms to help designers consume the card better.

**Comment by SimonLeclercq** [comment]
@Sabrinavigil @MARIEDELATTRE any news on this topic?

**Comment by MARIEDELATTRE** [comment]
We need to add a basic container on the 3 platforms and keep others variants like on web for this version.

**Comment by lauthieb** [comment]
Grooming session decision:
We close this and this will be took in the next major release.
