### ISSUE TITLE
Add a small size for Tag component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#15]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Add a small variation to tag with 12 font
@alexandre.kassem

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [x] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-android/issues/151
- [ ] https://github.com/Decathlon/vitamin-compose/issues/59
- [ ] https://github.com/Decathlon/vitamin-web/issues/1319
- [ ] https://github.com/Decathlon/vitamin-ios/issues/103
```

**Comment by lauthieb** [comment]
Will not be resolved on Vitamin iOS due to important note, so I close this issue.
