### ISSUE TITLE
Bug on Rating - Read only

### ISSUE THREAD

**Issue by VictorFF-Spain** [Decathlon/vitamin-design#150]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

We have detected an error in “Rating - Read Only”. The error is that the component has the same interaction as “Rating - Interactive” and must be only read.

### Expected behavior 🤔

We expect only read behavior, so when you click on the component, the stars not changes.

### Context 🔦

We had a problem with the QA team because they thought the expected behavior would be different in the prototype.

### Screenshots / Videos 📸

https://user-images.githubusercontent.com/121301574/209351730-a03719b0-4fda-4910-b95b-b710a099d7ce.mov

**Comment by lauthieb** [comment]
Hi @VictorFF-Spain, thanks for your request, and sorry for the delay.
We'll keep you informed as soon as possible.

**Comment by VictorFF-Spain** [comment]
Thanks team!
