### ISSUE TITLE
Add a new <volume-alert>

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#152]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

volume-alert

### Icon or Asset description

<img width="1071" alt="Capture d’écran 2023-01-04 à 18 42 18" src="https://user-images.githubusercontent.com/65814825/210616938-51daaec9-4bfb-411d-acc5-34aed2a0ebbc.png">
Thanks @Loic

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

https://github.com/Decathlon/vitamin-design/issues/152#tasklist-block-fe7f16f9-4ba3-4b6d-af8a-882e69d44c23

**Comment by lauthieb** [comment]
Done for web: <img width="890" alt="CleanShot 2023-01-09 at 23 07 58@2x" src="https://user-images.githubusercontent.com/9600228/211418156-9b7dd5da-51f8-4450-ad97-535442cd58ab.png">
