### ISSUE TITLE
Add <Zeplin> to the allowlist

### ISSUE THREAD

**Issue by ollyliu** [Decathlon/vitamin-design#153]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin name

Zeplin

### Figma plugin URL

https://www.figma.com/community/plugin/745330164019088593/Zeplin

### Why do you need this Figma plugin?

Hi 
With Zeplin it will be quite handy for designers to create different user flow to the vender. It will also be more efficient for developers to keep their screen on figma files checking the handoff design also understand the user flow on Zeplin.
However it is not mandatory to allow this plugin I also wonder if there is any other similar plugin that I don't know but works the same the team already allow the plugin usage ? Thank you :)

**Comment by lauthieb** [comment]
Hello @ollyliu,
As discussed together, we will close this issue.
Thanks again for this proposal.
