### ISSUE TITLE
Add widget jira-for-figjam to the allowlist

### ISSUE THREAD

**Issue by bernard-klymowicz** [Decathlon/vitamin-design#156]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin/widget name

jira-for-figjam

### Figma plugin/widget URL

https://www.figma.com/jira-for-figjam/

### Why do you need this Figma plugin/widget?

Team app mobile use figjam for "user stories" conception.
It is a good tool to open the discussion on user needs, clarify the rules to be implemented, give examples to facilitate understanding.
As we use Jira to monitor our work in progress, this widget allows us to :
- create a jira ticket very quickly as soon as we create a user story in figma without having to waste time connecting to jira
- quickly identify the user stories that have been created in jira and see an up-to-date status (as it is possible to synchronise the ticket with jira)

**Comment by lauthieb** [comment]
Hello @bernard-klymowicz, thanks for this proposition.
As we use Jira officially at Decathlon, I just approved it.
Enjoy :)
