### ISSUE TITLE
[Tabs] Icon colors bug

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#159]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

The color of the icons tabs has been reset in the figma library

<img width="1655" alt="Capture d’écran 2023-01-06 à 18 49 39" src="https://user-images.githubusercontent.com/65814825/211069506-51c019d0-1e1e-4fe0-bcda-43a16bc11cf0.png">

**Comment by MARIEDELATTRE** [comment]
I've made a new branch there was too much conflicts on the old one. Review send to @SimonLeclercq 


![Image](https://user-images.githubusercontent.com/61324309/214679981-e258656d-6a63-4054-b730-313d9ddb5845.png)

**Comment by lauthieb** [comment]
Done in vitamin-web ✅
