### ISSUE TITLE
Usage section is missing for quantity component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#16]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

When we go in quantity component page, we can see Overview, Web, Android and iOS sections but not "Usage" section which describe advanced common specification accros all platforms.

That can be cool to add this section and add some do/don't usage of this component.

@GerardPaligot

**Comment by lauthieb** [comment]
@GerardPaligot feel free to reopen if it's still needed.
