### ISSUE TITLE
Add Checkbox widget to the allowlist

### ISSUE THREAD

**Issue by bernard-klymowicz** [Decathlon/vitamin-design#160]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin/widget name

Checkbox

### Figma plugin/widget URL

https://www.figma.com/community/widget/1128418075386021939/Checkbox

### Why do you need this Figma plugin/widget?

Team app mobile use figjam for "user stories" conception.
the team uses this checkbox widget to quickly see what is ok or not in the US definition of ready checklist.
So we can validate each item of our checklist quickly just by clicking on the widget (instead of replacing the item by a checkbox checked or unchecked according to its status)

**Comment by lauthieb** [comment]
Hi @bernard-klymowicz, thanks for this proposal.
Approved ✅ 
Enjoy 🎉
