### ISSUE TITLE
PRICE > Strikethrough > XSmall 12

### ISSUE THREAD

**Issue by AlexNacache** [Decathlon/vitamin-design#161]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

It would be nice to have the component "price > variant "Strikethrough" in size XSmall with a text body of 14

### Dependencies 📦

This is the Price component

### Examples 🌈

<img width="1054" alt="Capture d’écran 2023-01-10 à 15 52 13" src="https://user-images.githubusercontent.com/122098718/211583861-55ea5461-e229-4f4a-a5cf-b1e128cc3137.png">

### Motivation 🔦

I am working on the different variants of the price component that can be found on PLP and PDP.

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by lauthieb** [comment]
Related PR: https://github.com/Decathlon/vitamin-web/pull/1329
@Sabrinavigil can you merge this now on Figma? Thanks!
