### ISSUE TITLE
[Quantity Picker] Make QuantityPicker extensible

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-design#162]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [X] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

Actually, QuantityPicker has a fixed size. 
But depending on the content we need to make it extensible.
Need Design validation & documentation update before Tech modifications. 

### Examples 🌈

![image](https://user-images.githubusercontent.com/46710837/212301869-ee4bc8c2-8520-4be6-8e0e-6649ac0fab5b.png)

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-compose/issues/102
- [ ] https://github.com/Decathlon/vitamin-web/issues/1356
```

**Comment by SimonLeclercq** [comment]
Contribution done, Documentation to be updated with examples.

**Comment by SimonLeclercq** [comment]
Android ✅ 
Web ✅

**Comment by SimonLeclercq** [comment]
the design is under review, awaiting validation before going to documentation
