### ISSUE TITLE
Android Collapsing toolbar

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-design#163]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

Here the request for having a collapsing toolbar 

https://decathlon-design.slack.com/archives/C01M569MN8L/p1670941275534269

It is link to the issue https://github.com/Decathlon/vitamin-design/issues/142

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by lauthieb** [comment]
Decision in grooming session:
- Validated by @Decathlon/design-system-core-team-design 
- To do in vitamin-android & vitamin-compose

**Comment by lauthieb** [comment]
As it's a validated & dev only issue, I close this issue here and just split this subject into two issues for Androdi & Compose implementations:
- https://github.com/Decathlon/vitamin-android/issues/166
- https://github.com/Decathlon/vitamin-compose/issues/104
Thanks!
