### ISSUE TITLE
Add a new variation of the Select component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#164]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

@AlexNacache 
A new variation without border as the exemple

### Examples 🌈

![unnamed2](https://user-images.githubusercontent.com/65814825/213149039-92839932-731c-4cef-b09e-e56da8b56dc0.png)

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [x] Figma branch merged
- [x] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1357
```

**Comment by MARIEDELATTRE** [comment]
is it only for select? or also dropdown component?
+ the documentation need to be updated

**Comment by AlexNacache** [comment]
@MARIEDELATTRE  This is only for the select, the dropdown does not change.
See this example in the attachment.
<img width="983" alt="Capture d’écran 2023-01-26 à 09 33 28" src="https://user-images.githubusercontent.com/122098718/214790866-61e66b72-719b-40bf-8747-29cf0e61b741.png">

**Comment by SimonLeclercq** [comment]
Documentation is update, ready for code implementation
