### ISSUE TITLE
List component with the title and subtitle going to the line

### ISSUE THREAD

**Issue by AlexNacache** [Decathlon/vitamin-design#166]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

We would like to be able to put more than one line for the title and subtitle of the "List" component

### Dependencies 📦

Search autocomplete results part.

### Examples 🌈

![image](https://user-images.githubusercontent.com/122098718/213464271-050eb4c9-2968-4a14-8080-6ea07b337c7e.png)
![image (1)](https://user-images.githubusercontent.com/122098718/213464307-654f0300-df56-447f-9fc4-66b11d28a05b.png)

### Motivation 🔦

We are working on a new version of the autocomplete search and we need to pass the title to the line when the result is too long.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
Thank you @AlexNacache ! :)

**Comment by lauthieb** [comment]
Done ✅ https://github.com/Decathlon/vitamin-web/commit/daa0f126df79b6a76c4e89bac6ef4afa43b382ad
Thanks @AlexNacache & @Mig-L :)
