### ISSUE TITLE
Improve price component by removing padding for default and strikethrough variants

### ISSUE THREAD

**Issue by EGilleron** [Decathlon/vitamin-design#167]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

For the default and strikethrough variant there is no background but there is a padding-inline.
I propose to remove padding-inline for these two variants.

### Examples 🌈

Actually : 
![image](https://user-images.githubusercontent.com/73116933/213488791-f1a426eb-5371-4ae3-9a7c-86bd3b55cd08.png)

Expected :
![image](https://user-images.githubusercontent.com/73116933/213488962-656ea74d-6f87-477d-bc86-a746ba1ba56f.png)

### Motivation 🔦

Trying to have the strikethrough price like the screen :
![image](https://user-images.githubusercontent.com/73116933/213489176-860d0203-4de0-4543-af0f-6b7de904f2c2.png)

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by MARIEDELATTRE** [comment]
We can aslo remove padding from default variant as well :)

**Comment by EGilleron** [comment]
> Yeah, of course, it's written in the desc :)

**Comment by lauthieb** [comment]
Merged https://github.com/Decathlon/vitamin-web/pull/1341

**Comment by lauthieb** [comment]
I reopen this ticket (cf. my email)

**Comment by MARIEDELATTRE** [comment]
The figma branch "#167 no-padding-variant-added" is under review.

**Comment by lauthieb** [comment]
Hi @MARIEDELATTRE, thanks! I just approved on my side, feel free to merge & publish on Figma :)

**Comment by SimonLeclercq** [comment]
From review -> Done

**Comment by lauthieb** [comment]
Done in vitamin-web: https://github.com/Decathlon/vitamin-web/pull/1343
