### ISSUE TITLE
Change icon / asset size from 16px to 24px in develop export

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#168]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [X] Vitamin Icons
- [X] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

By default, an icon or an asset have a size to `24dp` (px) but the current size in Figma is `16px`. That could be nice to scale up the size of the icon to `24px`.

### Motivation 🔦

It will be useful in icon/asset generators to avoid an initial scale in XML and Kotlin files to `24dp` but with a viewport size to `16dp`.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
@lauthieb is it ok for the web? No impact?

**Comment by lauthieb** [comment]
@Sabrinavigil, can we test with one svg with old export & one with the newer?
With this, I would be able to test if we have impact in output.
Thanks

**Comment by SimonLeclercq** [comment]
@thibault-mahe branch `#168` on `Vitamin-Icons` ready for your test ☺️

**Comment by lauthieb** [comment]
Thanks @SimonLeclercq

Here is the diff when I download from Figma (old vs. new `svg` files): 
![CleanShot 2023-01-23 at 17 31 13](https://user-images.githubusercontent.com/9600228/214095020-7216b344-4df1-40f1-8d42-a85247038b1a.png)

After our `build` phase with `svgo` on vitamin-web _(that cleans dimensions like width/height & attrs like `stroke`, `fill` & `color`)_, here is the diff (old vs. new `svg` files): 
![CleanShot 2023-01-23 at 17 34 17](https://user-images.githubusercontent.com/9600228/214095682-c9b0f27b-9594-478c-9a07-09056b8b6e72.png)

So, from my point of view, regarding vitamin-web:

✅ OK for "Icon font" usage, no breaking.
![CleanShot 2023-01-23 at 17 35 33](https://user-images.githubusercontent.com/9600228/214096121-1a5ae107-b233-4e22-89be-8e9476d056dd.png)

🚧 I don't know for "Sprite" usage, can you please help me @thibault-mahe? 🙏 

✅ OK for "External image" usage (e.g. using this `svg` thanks to our CDN in a `img` tag), no breaking. 

✅ N/C for "CSS" usage as it's copy/paste inside CSS of our consumers' apps.

✅ N/C for "Embedded" usage as it's copy/paste inside CSS of our consumers' apps.

For more details regarding usage methods of `@vtmn/icons`: https://www.npmjs.com/package/@vtmn/icons

**Comment by SimonLeclercq** [comment]
@thibault-mahe let me know when your test will be ok 👍

**Comment by thibault-mahe** [comment]
I agree with @lauthieb on all his validations and I add that there is no consequence on the sprite either (tested). No problem on the web side to make this change on Figma 👍 
Thanks!
