### ISSUE TITLE
Different colors on GREY 400

### ISSUE THREAD

**Issue by VictorFF-Spain** [Decathlon/vitamin-design#169]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [X] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

Using the class border-inactive, we have noticed that the color GREY 400 in the documentation for devs has a different color code than in Figma.
GREY 400 in [documentation](https://www.decathlon.design/726f8c765/p/85c5a1-colors/b/11bec5) = #8C96A2
GREY 400 in Figma = #8996A2

**Comment by lauthieb** [comment]
Hello @VictorFF-Spain,
It was a typo on Figma, you're right! Thanks for reporting this.
I just fixed it :)
