### ISSUE TITLE
 Icons have some properties which are differents in Figma

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#172]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [X] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

I've select all with same properties and some icons are not selected we need to investiguate why
<img width="1151" alt="Capture d’écran 2023-01-25 à 11 53 16" src="https://user-images.githubusercontent.com/61324309/214547346-91ab35ae-d3b5-4c82-a1df-6d018a24552e.png">

**Comment by SimonLeclercq** [comment]
hardly looking where it comes from..

**Comment by lauthieb** [comment]
Same!
I already found some things in a branch #172 B thanks to a hand-made Figma plugin to track differences between layers.
I'll keep you informed.

**Comment by MARIEDELATTRE** [comment]
Reviewed and merge the 22 changed (not published), the initial branch have been archived.
