### ISSUE TITLE
Interchanged position names

### ISSUE THREAD

**Issue by SalomeKib** [Decathlon/vitamin-design#177]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

The variables top and bottom are interchanged. 
-> If I select a popover with the position Top right, I will get a Bottom right popover.

### Expected behavior 🤔

The name of the position should match the popover.

### Context 🔦

Using the component to build an interface that needed a Top right popover. 

### Screenshots / Videos 📸

![image](https://user-images.githubusercontent.com/108399512/215725099-7033bec1-9a57-44c4-9684-e365e0462029.png)

**Comment by SalomeKib** [comment]
the attribute « position » is the position of the popover body relatively to its arrow.

**Comment by lauthieb** [comment]
Thanks @SalomeKib!
