### ISSUE TITLE
Accessibility statement in our documentation

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#18]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

Update the Accessibility statement in Figma Community

**Comment by lauthieb** [comment]
Hello!
It's ok for me and will be bring in v0.20 of decathlon.design.
@Sabrinavigil I let you do it on Figma.
Thanks!
