### ISSUE TITLE
Add a new <ecodesign>

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#180]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

ecodesign

### Icon or Asset description

<img width="78" alt="Capture d’écran 2023-02-01 à 10 25 02" src="https://user-images.githubusercontent.com/61324309/216003227-03fbb96e-a2a2-4977-a9db-5b394f6237cc.png">
It exist an ecodesign icon on physical product, maybe we could adapt it for digital?

### Icon or Assets keywords

ecodesign, ecological

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by MARIEDELATTRE** [comment]
https://drive.google.com/file/d/1E95ZQ_VH1Tl0SbFRmTYfe6lC_inrjpQ2/view?usp=share_link

**Comment by MARIEDELATTRE** [comment]
I've tried different proposals, it's currently in design review
![Image](https://user-images.githubusercontent.com/61324309/216082976-fb3be8b9-1c35-492a-a99d-1775a92bbf91.png)

**Comment by lauthieb** [comment]
@MARIEDELATTRE from my point of view, I think in a label the second proposition is the best (due to small size).

**Comment by MARIEDELATTRE** [comment]
As the existing logo doesn't work in small size as digital icon, we advise Ilaria to use vitamix seed icons for ecodesign.
