### ISSUE TITLE
Improve documentation for components that are not applicable for mobile

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#184]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [X] Not related to one Figma library

### Summary 💡

We need to improve our documentation to be as clear as possible concerning the components that are not applicable.

- **Contribution** : we need to add in the decision tree that for non-applicable component contribution is not allowed because for most of the cases it exists other solutions to bypass this issue.
- **Component status** : Here again we can add an explanation of what is a non-applicable component and why
- **Tooltip/Popover** : In the overview we can add a sub-title "How do you decline on the mobile?"
- **New category pattern** : We can create a new pattern category within which we could add a "offering help" category especially for onboarding like the one [on apple](https://developer.apple.com/design/human-interface-guidelines/patterns/offering-help/#Resources)

### New 🆕

- [X] Validated in a grooming session

### Backlog 📋

- [X] Has a good summary
- [X] Has example link(s)

### Design in progress 🏗

- [X] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by MARIEDELATTRE** [comment]
Contribution ✅ [](https://www.decathlon.design/726f8c765/v/0/p/195920-contributing/b/04a4ff)
Component status ✅ [](https://www.decathlon.design/726f8c765/v/0/p/93ca3c-component-status)
Tooltip/Popover ✅ [](https://www.decathlon.design/726f8c765/v/0/p/595266-tooltip/b/97ce1d)
[](https://www.decathlon.design/726f8c765/v/0/p/3086dd-popover/b/129609)
New category pattern ✅ [](https://www.decathlon.design/726f8c765/v/0/p/03ebd3-guiding)

@SimonLeclercq et @ManonPolle I let you add your review directly on zeroheight :)

**Comment by SimonLeclercq** [comment]
Under review by Salomé, changelog written, waiting for publication
