### ISSUE TITLE
Loading state for vitamin button

### ISSUE THREAD

**Issue by Z08MURBE** [Decathlon/vitamin-design#186]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

As part of the processing of a US we realize that it would be relevant to have a loading state as a variant of the button component for some features.

### Examples 🌈

For example, this is useful when the button is linked to an action such as "download an invoice".

You can find attached the link to Prime react which illustrates the expected behavior well.
https://primereact.org/button/#loading

### Motivation 🔦

 It can be useful for the specificity to the user that his action has been taken into account but that a loading delay is associated.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by lauthieb** [comment]
Hello,
Thanks @Z08MURBE for your proposition. We know that it could be a good thing to add to our button.
Unfortunately, we will not be able to do it for our current version but I close your issue & add its reference to our issue related to the future button that we will build in our next major release: #7.
Thank you very much.
