### ISSUE TITLE
Inconsistency in actions color

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#188]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [x] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [x] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

The current action button inside the card is blue and the action button inside the list is grey

### Expected behavior 🤔

The button action inside component must have the same colors

### Context 🔦

Inconsistency between the different actions of the application

### Screenshots / Videos 📸

<img width="842" alt="Capture d’écran 2023-02-06 à 09 59 00" src="https://user-images.githubusercontent.com/100569235/216928584-5020f6e0-ed04-42ca-9624-2b915621830b.png">

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1370
```

**Comment by lauthieb** [comment]
Hi @felixbusadkt,
Thanks for reporting this.
We will talk about it this week with the team.
@Decathlon/design-system-core-team-design, I'm ready to help during the grooming.
Thank you.

**Comment by SimonLeclercq** [comment]
Merged on `ios`, `Android` and `web`

**Comment by lauthieb** [comment]
Hello,
The end action of the list component is still black. Is it normal?

![CleanShot 2023-02-13 at 17 19 37](https://user-images.githubusercontent.com/9600228/218513016-c0d82d0a-7769-4c7b-b6c9-0d23e282b941.png)

**Comment by SimonLeclercq** [comment]
To avoid breaking changes, and while waiting to decide on the implementation of the components properties, I propose not to make any changes for the moment
