### ISSUE TITLE
Snackbar on Web UI kit Figma isn't responsive

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#189]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

When we want to change snackbar (Right button true) width the button isn't fix to the right side.
<img width="578" alt="Capture d’écran 2023-02-07 à 11 44 08" src="https://user-images.githubusercontent.com/61324309/217223395-6c4f80ec-a6ae-403a-ae69-8727e02cd043.png">

The problem is aslo here on the default variant without button.

### Expected behavior 🤔

We should set the text to "fill container"

**Comment by SimonLeclercq** [comment]
👌
