### ISSUE TITLE
Design tokens

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#19]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Improve our color naming convention.
Rework our foundation to get ready for design token.

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [x] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by SimonLeclercq** [comment]
Technical choices made : 
- Selection of the `Figma tokens plugin` to manage the creation of tokens.
- Initialization of [Decathlon/Vitamin-design](https://github.com/Decathlon/vitamin-design) to host the truth source.
- Foundations are managed by the [Core Team](https://www.decathlon.design/726f8c765/p/79cf66-teams), used to generate a foundation library in Figma, then distributed through this library.

**Comment by SimonLeclercq** [comment]
Design token:
- `Typography` under review
- `Colors under` review
- `Spacing` under review
- `Border radius` under review
- `Layout` under review

**Comment by SimonLeclercq** [comment]
Architecture documentation & name charter will be documented through Vitamin-design repository
