### ISSUE TITLE
Improve documentation about theming

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#192]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

In the [theming documentation here](https://www.decathlon.design/726f8c765/p/88a9a6-theming/b/76262d) we let people believe that they can create themes which is not really true.

### Expected behavior 🤔

We need to rework this part to be clearer that core and light + dark are the only allowed themes in Vitamin?

**Comment by lauthieb** [comment]
Rename "Theming" => "Dark mode"
