### ISSUE TITLE
Add Multiline variant/option for text input in mobile

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#196]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [X] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

<img width="877" alt="CleanShot 2023-02-17 at 16 37 57@2x" src="https://user-images.githubusercontent.com/61324309/219698286-6d3d8123-a28b-4638-bc35-5f25c9c27221.png">

> to confirm if it's the case on iOS

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by MARIEDELATTRE** [comment]
@ManonPolle what do you think?

**Comment by ManonPolle** [comment]
In fact, this is already possible in `vitamin-compose` or `vitamin-android`.
By default, multi line is possible with an adaptative height depending on the content. 

But it is also possible to define the max lines height or block to 1 line.

here examples with `vitamin-compose`

<img width="353" alt="image" src="https://user-images.githubusercontent.com/46710837/221215081-88d9e699-a5fa-483e-b28c-ceb22e853e39.png">

**Comment by Sabrinavigil** [comment]
Tagged as next <3

**Comment by lauthieb** [comment]
A new ticket has been created on an inner source repository.
