### ISSUE TITLE
Snackbar component

### ISSUE THREAD

**Issue by baptistedajon** [Decathlon/vitamin-design#197]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [X] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

A snackbar is used to provide non-disruptive feedback about the outcome of an event.

Thanks to its implementation, we will not need Toast component anymore. (see https://github.com/Decathlon/vitamin-design/issues/27#issuecomment-1284561851)

Fyi, for iOS, a new implementation of a component which look like a snackbar in the official Apple Music App on iOS 16.4 
To keep in mind for the revamp of Vitamin iOS

### Examples 🌈

![twitter_FpJ0lI0XEAA15MM](https://user-images.githubusercontent.com/1397461/220314419-eda1b2c6-b3d6-404f-875e-6844e0a89c9f.jpg)
![twitter_FpJ0lI1X0AAmu7h](https://user-images.githubusercontent.com/1397461/220314431-652b2bee-bd3f-4a09-aa0f-acfae47661ca.jpg)
![twitter_FpJ0lI0X0AMgAhf](https://user-images.githubusercontent.com/1397461/220314439-1574501c-374d-4ce6-b85c-35cf7dd42e52.jpg)
![twitter_FpJ0lI0WYAEYjSD](https://user-images.githubusercontent.com/1397461/220314443-5e340758-61ad-4b8a-980d-4a166dfab711.jpg)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by ManonPolle** [comment]
A new ticket has been created on an inner source repository
