### ISSUE TITLE
Add EightShapes Specs to the allowlist

### ISSUE THREAD

**Issue by Almadasilva** [Decathlon/vitamin-design#204]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin/widget name

EightShapes Specs

### Figma plugin/widget URL

https://www.figma.com/community/plugin/1205622541257680763/EightShapes-Specs

### Why do you need this Figma plugin/widget?

Because it can really help us (better than Redlines). 🤓😍

**Comment by Sabrinavigil** [comment]
Approved :)
