### ISSUE TITLE
Add a new wifi-off icon

### ISSUE THREAD

**Issue by SimonRoger1988** [Decathlon/vitamin-design#205]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

Wifi-Off

### Icon or Asset description

It allows the user to indicate a lack of internet connection.
Use case: Inform the user that the experience may be degraded due to a lack of network. It then goes into offline mode.

### Icon or Assets keywords

wifi, network, connection, wireless

### Icon or Asset author

Remix Icon

### Icon or Asset SVG code

```shell
<svg>Wifi-Off</svg>
```

### Are there any other important details?

There is another issue about Wifi-On icon
[Link here](https://github.com/Decathlon/vitamin-design/issues/206)
__________

There is an icon to say RSS, it's similar on the shape, but it's differents in the meaning

**Comment by Sabrinavigil** [comment]
thanks @SimonRoger1988 :)
