### ISSUE TITLE
Add a new keyboard icon

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#209]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

Keyboard

### Icon or Asset description

Used to represent keyboard inside mobile time pickers

### Icon or Assets keywords

keyboard

### Icon or Asset author

Remix Icon

### Icon or Asset SVG code

```shell
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M4 5v14h16V5H4zM3 3h18a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm3 4h2v2H6V7zm0 4h2v2H6v-2zm0 4h12v2H6v-2zm5-4h2v2h-2v-2zm0-4h2v2h-2V7zm5 0h2v2h-2V7zm0 4h2v2h-2v-2z"/></svg>
```

### Are there any other important details?

<img width="332" alt="Capture d’écran 2023-03-06 à 18 08 35" src="https://user-images.githubusercontent.com/100569235/223181100-0ca39063-3b49-4ad7-a368-95b27610f627.png">

**Comment by Sabrinavigil** [comment]
thanks @felixbusadkt
