### ISSUE TITLE
Contribution companion pages are redirecting to our old Jira board instead of our GitHub project board

### ISSUE THREAD

**Issue by SimonLeclercq** [Decathlon/vitamin-design#21]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

when I read the contribution documentation, I'm redirect to the Design System Backlog. The problem is that it directs me to Jira (not up-to-date and not accessible from outside)

### Expected behavior 🤔

As a user, I would like to be redirect to [Decathlon Design System Board](https://github.com/orgs/Decathlon/projects/3) for all our Design files. Then, republish them to Figma Community (Open Source).

### Context 🔦

I wanted to check what the team is working on.

### Screenshots / Videos 📸

<img width="623" alt="issue-screen-shot" src="https://user-images.githubusercontent.com/50582328/179787413-44939f7a-b973-4371-bce5-17525521bbde.png">

**Comment by Sabrinavigil** [comment]
no dev impact
