### ISSUE TITLE
Adapt Accessibility Statement for Mobile Platforms

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#215]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [X] Not related to one Figma library

### Summary 💡

The accessibility statement is not suitable for the android platform or any type of mobile device as links in the text are not allowed due to accessibility.

Link of the current accessibility statement: https://www.figma.com/file/2OGKcDZskgeJXZVz7O8vNr/Declaration_d-accessibilite?node-id=0-1&t=8phqG0eKefx5xfCh-11

### Examples 🌈

https://www.figma.com/file/3oIJG26TG2F4J70232Wrgj/branch/KM6gndAYo0khfJukAbkJCn/%E2%9A%99%EF%B8%8F-Settings?node-id=902-4449&t=KqMlvbAPGHNJTkwf-11

### Motivation 🔦

Adapt the links of the web accessibility statement for Android and iOs platforms

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
Hi felix, the accessibility statement is for web, do you develop it ? it's a web-view

**Comment by felixbusadkt** [comment]
My team want to develop it for his application (Cube-InStore), so we need to develop it in web-view? I'll discuss this with my Tech Lead and get back to you

**Comment by lauthieb** [comment]
@felixbusadkt did you have some news regarding this? I think a web view could be enough for this.

**Comment by felixbusadkt** [comment]
My team currently develop it for Android in compose, you can contact Adrien Busin (adrien.busin@decathlon.com) he is the developper in charge.

**Comment by lauthieb** [comment]
Hello,
As discussed in grooming session with the team, we decided to propose a markdown format which will be simpler to import and convert for mobile platforms.
Here is it in production: https://decathlon.zeroheight.com/styleguide/s/35776/p/46028c-accessibility/b/074479
Thank you again @felixbusadkt for your contribution.
