### ISSUE TITLE
Thumb of a Toggle in dark mode is too dark

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#216]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [x] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

When I configure a toggle in dark mode, the thumb is too dark and isn't enough visible.

### Expected behavior 🤔

A different color for the thumb when I configure my UI in dark mode.

### Screenshots / Videos 📸

![image](https://user-images.githubusercontent.com/1913901/224090457-c11d0a43-0362-4f0e-a944-91fe4c3293f2.png)

### Tasklist

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1430
- [ ] https://github.com/Decathlon/vitamin-compose/issues/147
- [ ] https://github.com/Decathlon/vitamin-android/issues/185
```

**Comment by Sabrinavigil** [comment]
@ManonPolle :)

**Comment by Sabrinavigil** [comment]
Same for web and ios

**Comment by MARIEDELATTRE** [comment]
already fixed on iOS.
Done and published on android and web
