### ISSUE TITLE
Add GitHub Widget to the allowlist

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#217]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin/widget name

GitHub

### Figma plugin/widget URL

https://www.figma.com/community/widget/1101944648482192724

### Why do you need this Figma plugin/widget?

Here is a playground to explain : https://www.figma.com/community/file/1103764168304142262

**Comment by lauthieb** [comment]
Thanks @Sabrinavigil, I completely agree and accepted it as we use GitHub and it's an official widget from Figma. ✅
