### ISSUE TITLE
[IOS] Top Navigation Component (IPhone X)

### ISSUE THREAD

**Issue by AurelienVanPraet** [Decathlon/vitamin-design#219]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [X] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

The margin on the component IOS [Navigation_Bar] for iPhone X (Default) have a big margin under the title (42px) 

### Expected behavior 🤔

The margin should be the same of the component [Top_Navigation] for IPhone 6/7/8/SE (default status)

### Context 🔦

I want use the good component in my UI but it's complicated with this margin :) 

### Screenshots / Videos 📸

I have a comparison with Apple guidelines 

![Capture d’écran 2023-03-13 à 15 57 57](https://user-images.githubusercontent.com/118361698/224755504-fc74159e-a76c-4a63-91fd-7299fd7fd357.png)

**Comment by MARIEDELATTRE** [comment]
@AurelienVanPraet fixed and published thank you for contributing to resolve this bug. Sorry for the delay :)
