### ISSUE TITLE
UI Issue - Hight is not same of the product box 

### ISSUE THREAD

**Issue by ParveenAcewebx** [Decathlon/vitamin-design#22]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Screenshots / Videos 📸

![ui-issue](https://user-images.githubusercontent.com/107178641/179973326-1724764c-3ed6-4daf-bd96-b4106e5bfd1d.png)

**Comment by ParveenAcewebx** [comment]
URL: https://www.decathlon.in/search?query=bike%20pannier

**Comment by lauthieb** [comment]
Closed as reported to the relevant team. Thanks again!
