### ISSUE TITLE
20px margin on mobile

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#221]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [X] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

We still provide guidelines and figma layout with 20px margins on mobile instead of 16px

### Expected behavior 🤔

We should have 16px margins on mobile.

**Comment by lauthieb** [comment]
As discussed, we will do this in our next release because a lot of impact and breaking changes.
