### ISSUE TITLE
Add Select into Text Field

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#222]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

Add a selection control into text field to choose a data that depend the textfield

### Examples 🌈

<img width="389" alt="Capture d’écran 2023-03-17 à 15 20 30" src="https://user-images.githubusercontent.com/100569235/225931328-4f59f86c-1ebf-4774-8230-d9bc35216d62.png">
![Screenshot_20230317-154209](https://user-images.githubusercontent.com/100569235/225937625-636a7abe-4246-4082-9a77-b6cb7dfc1312.png)

### Motivation 🔦

Need it to select a country indicator for phone number 

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
thanks @felixbusadkt I let it open for the next version :)

**Comment by lauthieb** [comment]
A new ticket has been created on an inner source repository (issue below included).
https://github.com/dktunited/vitamin-play/issues/26
