### ISSUE TITLE
Add Flag Asset into Text Field

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#223]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [X] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

Add a flag into a text field to display the country you choose

### Examples 🌈

![IMG_3130](https://user-images.githubusercontent.com/100569235/225938635-4947ab63-497a-4dbc-999c-97ee4c76788c.jpg)
![IMG_3131](https://user-images.githubusercontent.com/100569235/225938655-4ad56314-908a-4fbf-9e14-8ddf42b65036.jpg)
![IMG_3131](https://user-images.githubusercontent.com/100569235/225938687-05ad2d13-31c9-4298-8c44-df20cbccff67.jpg)
<img width="469" alt="Capture d’écran 2023-03-17 à 15 48 43" src="https://user-images.githubusercontent.com/100569235/225938802-d488fd63-a96e-4653-8b42-22e69180f945.png">

### Motivation 🔦

Be able to display the country choose by the customer in addition to the text

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

**Comment by Sabrinavigil** [comment]
Thank you @felixbusadkt I let this issue open for the next version :)

**Comment by lauthieb** [comment]
A new ticket has been created on an inner source repository (issue below included).
https://github.com/dktunited/vitamin-play/issues/26
