### ISSUE TITLE
Badges for GooglePlay and AppStore

### ISSUE THREAD

**Issue by joserra84** [Decathlon/vitamin-design#226]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Assets

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

downloadAppStore && downloadPlayStore

### Icon or Asset description

It will be a badge button with the functionality and style of official AppleStore and GooglePlay Badget. 
# Documentation
https://developer.apple.com/app-store/marketing/guidelines/
https://play.google.com/intl/en_us/badges/

Action: click Action must be possible for navigate to an URL. 
Language configuration is mandatory in parameter configuration (google badge generator have a language selector for final language text on png generated.

![image](https://user-images.githubusercontent.com/89583160/227221542-61488503-e0c9-4489-8a6d-3d2bcf82244a.png) | ![image](https://user-images.githubusercontent.com/89583160/227221676-63c8680e-ed62-48a3-9aa8-fe8c34db95ce.png)

### Are there any other important details?

Badge Generator include a language, url..., must be mandatory for visual and click event.

**Comment by lauthieb** [comment]
Hi @joserra84, thanks for your proposition.
We will investigate with the team as soon as possible :)

**Comment by lauthieb** [comment]
Hi @joserra84,

We discussed with the team, we will do in our documentation "Platforms" guidelines and let the source of truth to the links you mentioned.
I'll keep you informed when these pages will be in production in our guidelines.

Thanks!

**Comment by lauthieb** [comment]
> Hi @joserra84,
> 
> We discussed with the team, we will do in our documentation "Platforms" guidelines and let the source of truth to the links you mentioned. I'll keep you informed when these pages will be in production in our guidelines.
> 
> Thanks!

Done in production:
- Android platform: https://www.decathlon.design/726f8c765/p/54c71f-platforms/t/13c375
- iOS platform: https://www.decathlon.design/726f8c765/p/54c71f-platforms/t/982a39
