### ISSUE TITLE
Add file-copy icon to Vitamix

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#23]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

file-copy

### Icon description

Concept: Used to copy to clipboard

### Icon keywords

copy, file, clipboard

### Icon author

Remix

### Icon SVG code

[RemixIcon_SVG_2207211001.zip](https://github.com/Decathlon/vitamin-design/files/9157433/RemixIcon_SVG_2207211001.zip)

### Development issues

- [x] https://github.com/Decathlon/vitamin-web/issues/1254
- [ ] TODO vitamin-android
- [ ] TODO vitamin-compose
- [ ] TODO vitamin-ios

**Comment by MARIEDELATTRE** [comment]
@jordivivesDKT thanks for contributing to this issue :)

**Comment by MARIEDELATTRE** [comment]
@jordivivesDKT the branch has been merged and the lib published with the new icon, I move the ticket to dev process to have it on all our dev libraries :)

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
