### ISSUE TITLE
Add Redlines & Annotations to the allowlist

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-design#238]
### Duplicates ❌

- [X] I have searched the existing Figma plugins requests.

### Figma plugin/widget name

Redlines & Annotations

### Figma plugin/widget URL

https://www.figma.com/community/plugin/1228826129267290034

### Why do you need this Figma plugin/widget?

To annotate Figma file

**Comment by lauthieb** [comment]
Done ✅
