### ISSUE TITLE
Add multiple editors icons

### ISSUE THREAD

**Issue by Remyvienne-partner** [Decathlon/vitamin-design#240]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

/ 

### Icon or Asset description

Action: Used to edit text : alignment, bold, font-size.
Wayfinding: Icons to help the user in editing his text.
We don't currently have any icons that represent text editing in vitamin.
All icons are available in the Remix library.
[Icons-editor-Pop-Remix.zip](https://github.com/Decathlon/vitamin-design/files/11295933/Icons-editor-Pop-Remix.zip)

### Icon or Assets keywords

text, alignment, font-size

### Icon or Asset author

Remix library

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
Thanks for your issue I take a look :)

**Comment by Sabrinavigil** [comment]
Icons added :

align-bottom
align-center
align-vertically
align-right
align-left
align-top
text
bold
font-size
