### ISSUE TITLE
Add multiple icons - Pop project

### ISSUE THREAD

**Issue by Remyvienne-partner** [Decathlon/vitamin-design#241]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

/ 

### Icon or Asset description

template icon: used to delimit a number of areas. help users understand how many areas they are working on.
designs icon: used to illustrate a library of components, illustrations and logos. help users understand that they will find a component library to import.
jersey-number icon: used to represent jersey markings, in particular numbers. help users understand that they will be able to add a number.
text-curved icon: used to curve text. help users understand that they will be able to curve a text
[Icons-Pop.zip](https://github.com/Decathlon/vitamin-design/files/11297015/Icons-Pop.zip)

### Icon or Assets keywords

template, designs, jersey-number, text-curved

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by MARIEDELATTRE** [comment]
Design and templates icons have been deleted to this contribution because there aren't agnostic of a product.
Italic have been directly added from remix.
