### ISSUE TITLE
Add new <arrow-[left and right]-double> icons

### ISSUE THREAD

**Issue by Benhayez** [Decathlon/vitamin-design#244]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [x] I have searched if the icon is already available on Remix.

### Icon or Asset name

arrow-left-double and arrow-right-double

### Icon or Asset description

Action : Used to denote the very end or the very beginning of a list
Wayfinding  : Used to help users Icons to go at the end of the list or go back to the beginning
Concept : used to represent that there is a beginning and a end to a list of elements in a page.
Education : Used to give users more information about the how he can go back to the beginning o go at the end of a list

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
Thank you for your contribution. Unfortunately, we won't be able to add any more icons as we need to focus on the new version of the design system.
We understand this may cause some inconvenience, and I sincerely apologize for any disruption this may cause. The icons you currently have can still be used locally in your projects. 
They will be incorporated into the upcoming version, which is expected to be released in a few months.
Thank you once again for your understanding. Your contributions are greatly appreciated, and I'm confident that the new design system will bring many exciting improvements.
