### ISSUE TITLE
Add a new home-4

### ISSUE THREAD

**Issue by NStahmer** [Decathlon/vitamin-design#245]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

home-4

### Icon or Asset description

This icon will be used to represent the delivery method we have available in Spain "Home Delivery Confort", which is different from the "Home Delivery" (represented by Home-2) because in this case the package is delivered to your floor upstairs, not only downstairs. For example, with big items.

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by jordivivesDKT** [comment]
Hi team :) Since Neus just left the project I'll be following this requests. Any doubts or inquiries, you can send it straight to me.

**Comment by Sabrinavigil** [comment]
Thank you for your contribution. Unfortunately, we won't be able to add any more icons as we need to focus on the new version of the design system.
We understand this may cause some inconvenience, and I sincerely apologize for any disruption this may cause. The icons you currently have can still be used locally in your projects. 
They will be incorporated into the upcoming version, which is expected to be released in a few months.
Thank you once again for your understanding. Your contributions are greatly appreciated, and I'm confident that the new design system will bring many exciting improvements.
