### ISSUE TITLE
Add new icons to clean local overrides

### ISSUE THREAD

**Issue by NStahmer** [Decathlon/vitamin-design#246]
### Duplicates ❌

- [X] I have searched the existing icons or assets and requests.

### Which Figma library is concerned?

Vitamin Icons

### Remix icon check (only for icons)

- [X] I have searched if the icon is already available on Remix.

### Icon or Asset name

money-euro-circle / box-3 / coupon-3 / loop-right

### Icon or Asset description

In order to clean overrides, we are looking for alternatives to delete the current local icons that are not aligned with Vitamin or its style. For some of them we're not able to find a fit in Vitamin and therefore we are asking to add the following icons from Remix:

money-euro-circle: to represent a coin.
box-3 : to represent Augmented Reality
coupon-3: to represent coupons and cheques. We want to differentiate them from the gift card or loyalty card.
loop-right: to use in the content of circular economy, second life products, reconditioned, etc. 

### Icon or Asset SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
Thank you for your contribution. Unfortunately, we won't be able to add any more icons as we need to focus on the new version of the design system.
We understand this may cause some inconvenience, and I sincerely apologize for any disruption this may cause. The icons you currently have can still be used locally in your projects. 
They will be incorporated into the upcoming version, which is expected to be released in a few months.
Thank you once again for your understanding. Your contributions are greatly appreciated, and I'm confident that the new design system will bring many exciting improvements.
