### ISSUE TITLE
Order track&trace postnl points to incorrect country

### ISSUE THREAD

**Issue by Lotte-Verheyden** [Decathlon/vitamin-design#255]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

When ordering something from the webshop, there is a "track my order" button. This opens a new tab to the website of the delivery partner, in this case PostNL, with a URL of the following format: 
https://jouw.postnl.nl/track-and-trace/<parcel ID>-<country code>-<region code>
The parcel ID and region code were correct, but the country code said "NL", while it should have been "BE". As a result, the track&trace page said "parcel not found". When manually changing the URL to BE, it found the parcel. 

### Expected behavior 🤔

When a something is ordered to Belgium, the URL to the delivery partner contains "BE" instead of "NL".

### Screenshots / Videos 📸

<img width="850" alt="Scherm­afbeelding 2023-07-17 om 09 49 59" src="https://github.com/Decathlon/vitamin-design/assets/48100308/42610bfb-ba6e-4567-a406-2c8b01538752">
<img width="1113" alt="Scherm­afbeelding 2023-07-17 om 09 50 22" src="https://github.com/Decathlon/vitamin-design/assets/48100308/c8c51908-73cf-4130-9ea6-64eabf43c73a">
<img width="1178" alt="Scherm­afbeelding 2023-07-17 om 09 50 47" src="https://github.com/Decathlon/vitamin-design/assets/48100308/1555c7f2-ac8e-4865-9a16-0deb0e70248d">

**Comment by lauthieb** [comment]
Hello, sorry but you are there in the Design System repository which is not related to e-commerce.
Can you please contact the belgium support to understand how you can report this bug, please?
Thank you.
