### ISSUE TITLE
Add <Just-RTL> to the allowlist

### ISSUE THREAD

**Issue by bavaajith** [Decathlon/vitamin-design#257]
Dear Team, 

We've made some exciting improvements to our shopping app. Now, we have integrated RTL language support into our designs to make our app more accessible and user-friendly for right-to-left languages. To achieve this, we've found a plugin that effortlessly converts the layout from right to left while maintaining the text format.   This will be a huge boost to our productivity! 

Please find the below link. 

https://www.figma.com/community/plugin/1081525609675954053/Just-RTL

Could please whitelist the above plugin? 

Thank you.

**Comment by lauthieb** [comment]
That's ok for me, thanks @bavaajith!
