### ISSUE TITLE
Add a variant that works with background secondary for Skeleton component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#26]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Add a skeleton variation for background secondary 

![image](https://user-images.githubusercontent.com/65814825/180439685-5851d7c6-5aeb-4bbe-b882-93ead884177e.png)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
The background is tertiary on the Figma design, so it is a darker shade. Is this a problem in the code?

**Comment by lauthieb** [comment]
It's also tertiary in vitamin-web as you can see here in live: https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-structure-skeleton--overview
& here is the related source code: https://github.com/Decathlon/vitamin-web/blob/5ca93a7dadb60c96f401c04292ca56f25a4afd4e/packages/sources/css/src/components/structure/skeleton/src/index.css#L11
