### ISSUE TITLE
feat: add Mercado Pago payment assets

### ISSUE THREAD

**Issue by asanch54** [Decathlon/vitamin-design#262]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [x] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

Right now in Chile we're test OneCart, and we need other icons for payment methods, but I didn't find the payment that we need in Vitamin. I'm gonna add here [https://drive.google.com/drive/folders/1cMGxh1NdBEaZ3mvVQ39tkZkbPB451Z7z?usp=sharing](url)
![RGB_MercadoPago-B-cian-horiz](https://github.com/Decathlon/vitamin-design/assets/149714050/3e4fd848-6fe7-4c80-8221-87b82c7b8049)
![RGB_MercadoPago-A-horiz (1)](https://github.com/Decathlon/vitamin-design/assets/149714050/c7af429e-5766-4ac1-a913-f24ea1f252d5)

### Expected behavior 🤔

we need the payment here, but this information comes to vitamin
![image](https://github.com/Decathlon/vitamin-design/assets/149714050/6d6a4a79-f32b-4f84-aa6e-109f30218946)

### Context 🔦

We need the payment of "mercado pago"  in Vitamin

### Screenshots / Videos 📸

![image](https://github.com/Decathlon/vitamin-design/assets/149714050/0966fc62-e993-4dd3-b5e8-8a6bcdc80fe8)

**Comment by Sabrinavigil** [comment]
fixed as discussed by chat :)
