### ISSUE TITLE
Merge Android toast & snackbar

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#27]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Summary 💡

Merge Android toast and snackbar (48)

![image](https://user-images.githubusercontent.com/65814825/180441157-ffde5d66-055d-44eb-9636-e1b8e0cf9803.png)

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Is it only for android ?

**Comment by thibault-mahe** [comment]
I cannot see the difference between the two components. I think it also applies to the web packages
cc @lauthieb

**Comment by lauthieb** [comment]
@thibault-mahe @Sabrinavigil yes you're right.

We can do this for our future major release.

So, I close this issue (feel free to reopen if you're not ok)
And I close #74 
And I edited the description of #75.

Thanks!
