### ISSUE TITLE
Add a usage for Breadcrumb component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-design#29]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

We need to write a [guideline for the breadcrumb ](https://www.figma.com/file/BiWHJTZHHTLk0QBhDuFhbS/DR---Workshop?node-id=233%3A3241)component for its behavior in web mobile.

_Originally posted by Valentin Bourgeois._

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by MARIEDELATTRE** [comment]
![Image](https://user-images.githubusercontent.com/61324309/199725857-afa5419f-bbc0-438d-bfcc-95bab1f1fff7.png)
