### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#34]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Card refacto with Nathan Curtis method of sub components.

### Examples 🌈

https://medium.com/eightshapes-llc/subcomponents-753ce9f6600a

### Motivation 🔦

All the possible combinations with the current card are quite obscure.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Fyi: https://github.com/Decathlon/vitamin-design/issues/146

**Comment by ManonPolle** [comment]
A new ticket has been created on an inner source repository
