### ISSUE TITLE
[Card] Remove badge for "more items"

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#36]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

There is a badge as counter for "more items"

### Expected behavior 🤔

<img width="637" alt="Capture d’écran 2022-08-02 à 16 07 28" src="https://user-images.githubusercontent.com/65814825/185888104-109b68cf-6bec-4f11-8df6-e48dc72e1371.png">

**Comment by lauthieb** [comment]
@Sabrinavigil, can you please reupload your screenshot? It seems broken.
Thanks

**Comment by Sabrinavigil** [comment]
Done ✅
