### ISSUE TITLE
[Icon]: New icon ic_vtmn_qrcode

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#37]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### How will these icons be used?

Start a qrcode scanner

### Icon name

ic_qrcode (ic_vtmn_qrcode for android)

### Icon description

Action: Used to scan a qrcode or barcode

### Icon keywords

qrcode, scan, camera, barcode

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by Sabrinavigil** [comment]
--> nammed qr-scan

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
