### ISSUE TITLE
Add a new icon <ic_vtmn_report>

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#38]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### How will these icons be used?

Wayfinding: Used to help users to report undesirable behavior

### Icon name

ic_report (android ic_vtmn_report)

### Icon description

Wayfinding: Used to help users to report undesirable behavior

### Icon keywords

report, undesirable behavior

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by lauthieb** [comment]
Thanks @GerardPaligot for your proposal. We will investigate it as soon as possible.
Have a nice day,
Laurent

**Comment by Sabrinavigil** [comment]
Hi @GerardPaligot I think the icon named "feedback" match you need, let us know, if it's ok for you I close the issue 

![Image](https://user-images.githubusercontent.com/65814825/196427052-9bc06c46-7e0f-41a4-adda-2e0aea7d62cf.png)

**Comment by lauthieb** [comment]
Closed in favor to feedback icon as @Sabrinavigil said.
@GerardPaligot feel free to reopen if this icon doesn't fit your needs.
Thanks!
