### ISSUE TITLE
[Icon]: New icon ic_vtmn_github

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#39]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

ic_github (ic_vtmn_github)

### Icon description

Concept: Used to represent GitHub platform.

### Icon keywords

github, git, social, code

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
