### ISSUE TITLE
Decathlon favicon has a transparent background

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#40]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Assets

### Current behavior 😯

Hi Design system team.

I noticed that the decathlon favicon has a transparent background. That leads to some weird logo : 
![image](https://user-images.githubusercontent.com/65814825/185097014-519f12bd-3c48-4267-ab44-0105ace737ce.png)
Is it possible to force a white background?

Thanks ;)

**Comment by lauthieb** [comment]
@Sabrinavigil just tried to export (by using the export fort developers page) in `.svg` and it still doesn't work with a transparent background.

Just turned back this issue in "ready for design".

Thanks in advance 🙏 

![CleanShot 2022-10-19 at 21 09 28](https://user-images.githubusercontent.com/9600228/196782473-e3025f64-ed71-4d8a-90f7-75d5b070a334.gif)

**Comment by Sabrinavigil** [comment]
The logo in the export page seems to be a new component and not an instance.
It's fixed now, could you retry please ?

**Comment by lauthieb** [comment]
@Sabrinavigil, now that's ok, thanks!
It's in review: https://github.com/Decathlon/vitamin-web/pull/1291/files
Thanks 🙏
