### ISSUE TITLE
Modal has incorrect radius

### ISSUE THREAD

**Issue by charlottemougenot** [Decathlon/vitamin-design#41]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Current behavior 😯

On vitamin-android library and on material, modals have a radius (see [Dialogs / Theming](https://material.io/components/dialogs#theming))

### Expected behavior 🤔

We should have the same visual aspect on both design and implementation libraries

### Context 🔦

We don't have same component in design and vitamin-android library

### Screenshots / Videos 📸

Material specs : 
![Capture d’écran 2022-08-18 à 15 55 31](https://user-images.githubusercontent.com/54030002/185412832-9ce32358-7526-4898-a769-25295f4eb98b.png)

Screenshot of figma component :  
![Capture d’écran 2022-08-18 à 15 57 30](https://user-images.githubusercontent.com/54030002/185413296-b17ca9f8-4e25-4897-92c2-2f1b7c0a9e10.png)

Screenshot of vitamin-android sample : 
![Screenshot_2022-08-18-15-35-54-86_5718ac90fb9fac1e0ff66814035ae4fb](https://user-images.githubusercontent.com/54030002/185414331-a6e8f4b3-d9d7-4784-9c24-4de3a49e4db8.jpg)

**Comment by lauthieb** [comment]
Thanks a lot @charlottemougenot for your request.
We will check this as soon as possible.
Have a great day,
Laurent
