### ISSUE TITLE
[Tags] Add ellipsis text possibility

### ISSUE THREAD

**Issue by rcarondecathlon** [Decathlon/vitamin-design#42]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Summary 💡

When creating a `Tags` in an Android application, UX and developers should choose if the `Tag` is expendable or if the text inside could be ellipsis. It allows to have a fix dimension in the design and works with all languages (even if the text is bigger than the `Tag` )

### Dependencies 📦

- Vitamin Android
- Vitamin Compose

### Examples 🌈

https://www.figma.com/file/0CBXURfZjxvChaO6bZXNav/%5B01.-Alarm%5D-New-Design?node-id=0%3A1

### Motivation 🔦

For security application in Decathlon store, RFID Alarms shows a label of the type of detection (read, stolen, forced, ...) at the RFID gate. To be sure the provide the same design with all languages, we need to ellipsis the text. 

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Thanks @rcarondecathlon for your proposal.
We will check this as soon as possible.
Have a great day,
Laurent
