### ISSUE TITLE
Shadows design tokens

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#5]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Improve "shadow". Rework foundation to get ready for design token.

### Examples 🌈

https://polaris.shopify.com/tokens/depth

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by vieiraloic** [comment]
Can you add the possibility to change orientation of the shadow ?

Exemple for bottom fixed layout : 
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7301942/205122615-bd1b9800-d2ea-449c-8997-ee40d947382d.png">

**Comment by lauthieb** [comment]
This topic has been launched in beta test.
However, its status in the board no longer reflects the current reality, so it has been moved to our "New" column.
We will keep you informed of the different advances.
Thank you.
