### ISSUE TITLE
Add a new icon <hourglass>

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#54]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

Hourglass

### Icon description

Used for pending status

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by damiencgz-design** [comment]
![Hourglass Size=32](https://user-images.githubusercontent.com/80691465/191893124-9b8f1928-f35d-4a02-92fa-71bf27a43fd7.svg)

**Comment by Sabrinavigil** [comment]
Added in "other" section

**Comment by lauthieb** [comment]
Thanks @damiencgz-design @MARIEDELATTRE & @Sabrinavigil

Here are the links for the development follow-up:
- https://github.com/Decathlon/vitamin-web/issues/1301
- https://github.com/Decathlon/vitamin-android/issues/142
- https://github.com/Decathlon/vitamin-ios/issues/96
