### ISSUE TITLE
[Icon]: Modified the fill version of the search icon 

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#57]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

Search

### Icon description

<img width="71" alt="Capture d’écran 2022-09-27 à 12 17 25" src="https://user-images.githubusercontent.com/65814825/192500245-9ccecc9b-cba1-4c4e-b496-ec78e11581e3.png">

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
