### ISSUE TITLE
[Icon]: New icon add-circle

### ISSUE THREAD

**Issue by LoicVieira** [Decathlon/vitamin-design#58]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

add-circle

### Icon description

Action: Used to denote add action.
Wayfinding: Used to help users to add something.
Concept: Used to represent a plus.
Education: Used to give users more information about context **???????**.

Add-icon (already available in Vitamin) is not relevant for selected state. So we propose this add-circle-icon, exemple :
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/114481464/192525488-b49c44bb-27e7-483e-aa3a-2e86119eaf0e.png">

### Icon keywords

System

### Icon author

Loïc Vieira

### Icon SVG code

```shell
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g id="Size=24px, Fill=False">
<path id="Shape" d="M11 11V7H13V11H17V13H13V17H11V13H7V11H11ZM12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22ZM12 20C14.1217 20 16.1566 19.1571 17.6569 17.6569C19.1571 16.1566 20 14.1217 20 12C20 9.87827 19.1571 7.84344 17.6569 6.34315C16.1566 4.84285 14.1217 4 12 4C9.87827 4 7.84344 4.84285 6.34315 6.34315C4.84285 7.84344 4 9.87827 4 12C4 14.1217 4.84285 16.1566 6.34315 17.6569C7.84344 19.1571 9.87827 20 12 20Z" fill="#001018"/>
</g>
</svg>


<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g id="Size=24px, Fill=True">
<path id="Shape" d="M12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22ZM11 11H7V13H11V17H13V13H17V11H13V7H11V11Z" fill="#001018"/>
</g>
</svg>
```

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
