### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#59]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A dropdown is a list of options that have an immediate effect like filter or sort content on a page.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Link #28 
Hello, on Decathlon website, on the product list, we have a dropdown which I can see the availability of the product and the size. Today, this feature doesn't exist. It is possible to discuss to be integrated on the design? Thanks

Originally posted by @Tlahey

**Comment by MARIEDELATTRE** [comment]
A new ticket has been created on an inner source repository (issue below included).
