### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#60]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A select is a form input that allow users to choose an option from a list.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
We need to add an icon next to the label like the example below (see old [ticket #121](url) )

![Image](https://user-images.githubusercontent.com/61324309/210817059-99930c39-a5f5-4f4c-8659-7c0399765eec.png)

**Comment by mackoj** [comment]
A new ticket has been created on an inner source repository (issue below included).

https://github.com/dktunited/vitamin-play/issues/38
