### ISSUE TITLE
Bar component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#68]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A bar creates a global navigation for your experience.
NB: don't forget to add some documentation like lenght of the label and truncate option if needed

![Image](https://user-images.githubusercontent.com/61324309/197960320-fc0f929b-a23d-4248-937c-02ba1d46ff4d.png)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Will be tracked here: https://github.com/dktunited/vitamin-play/issues/44
