### ISSUE TITLE
Modal component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#72]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A modal is a simulated window that appears above the main content and requires user interaction.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by MARIEDELATTRE** [comment]
like Alexandre Kassem from ecom said, we need to add a side modal.

**Comment by Kasmis** [comment]
@MARIEDELATTRE here is the Figma for the Panel/Overlay component : https://www.figma.com/file/btWjmFKKJh7uZFXTfvcp5s/Side-Pannel?node-id=2%3A2&t=npxj2hfdqptFwoey-1

> like Alexandre Kassem from ecom said, we need to add a side modal.

**Comment by lauthieb** [comment]
A new ticket has been created on an inner source repository
