### ISSUE TITLE
Snackbar component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#74]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A snackbar is used to provide non-disruptive feedback about the outcome of an event.

Thanks to its implementation, we will not need Toast component anymore. (see https://github.com/Decathlon/vitamin-design/issues/27#issuecomment-1284561851)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
See https://github.com/Decathlon/vitamin-design/issues/27#issuecomment-1284561851

**Comment by lauthieb** [comment]
Closed, see #197
