### ISSUE TITLE
Link component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#8]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

Improve component with properties and token. 
Apply specific text style.

### Examples 🌈

[Link – Carbon Design System (https://www.carbondesignsystem.com/components/link/usage/) 
[Photon Design System](https://design.firefox.com/photon/components/links.html)

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by MARIEDELATTRE** [comment]
We should include the possibility to change the right icon for example to have a right chevron instead of external link. 
Do not allow the possibility to change with any icon : define a short list of icon available.

**Comment by ManonPolle** [comment]
A new ticket has been created on an inner source repository
