### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#84]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

A list is a continuous vertical group of data entries like text, icons or images.

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by Sabrinavigil** [comment]
Please contact @ajith about its contribution :
_"Recently we have created a Flexible List component which covers most of our "App List use cases" 

Please check this Below Document for your reference. 
[internal document] https://www.figma.com/proto/tAbtRCXGiTbGyJiELEASbG/Vitamin-Contribution?page-id=1%3A201&node-id=1%3A3262&viewport=374%2C494%2C0.31&scaling=contain&starting-point-node-id=1%3A3262

The component can be explored here. [internal document]  https://www.figma.com/file/tAbtRCXGiTbGyJiELEASbG/Vitamin-Contribution?node-id=1%3A978 "_

**Comment by SimonLeclercq** [comment]
https://github.com/Decathlon/vitamin-design/issues/188

**Comment by MARIEDELATTRE** [comment]
A new ticket has been created on an inner source repository (issues below included and Ajith tagued).
