### ISSUE TITLE
Bar documentation gif

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#9]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

Add the gif for the web nav bar on [this page of Decathlon.design](https://www.decathlon.design/726f8c765/p/165aa1-bar/t/127c0e) 

### Screenshots / Videos 📸

![image](https://user-images.githubusercontent.com/65814825/178744112-6ef07f6f-4699-443c-9b61-00a149c008b9.png)

**Comment by lauthieb** [comment]
I close this issue because it's "done" inside our project board.
Feel free to reopen if I'm wrong.
