### ISSUE TITLE
Add vertical padding for Snackbar component

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-design#90]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Android UI Kit

### Current behavior 😯

The figma specification of Android Snackbar use a Ghost button without any vertical padding.

### Expected behavior 🤔

We should add a top and bottom padding of 6dp for the button

### Context 🔦

The Android implementation can't respect the design specification described in Figma Android UI Kit project.

### Screenshots / Videos 📸

![image](https://user-images.githubusercontent.com/1913901/193031809-17e468dc-4f49-4226-8c63-32aa28928593.png)

```[tasklist]

- [ ] https://github.com/Decathlon/vitamin-compose/issues/54
- [ ] https://github.com/Decathlon/vitamin-android/issues/149
- [ ] https://github.com/Decathlon/vitamin-compose/issues/55
```

**Comment by lauthieb** [comment]
Thanks @GerardPaligot for your bug report.
We will investigate it as soon as possible.
Have a nice evening,
Laurent

**Comment by Sabrinavigil** [comment]
linked https://github.com/Decathlon/vitamin-design/issues/25
