### ISSUE TITLE
Spacings design tokens

### ISSUE THREAD

**Issue by SimonLeclercq** [Decathlon/vitamin-design#91]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Define and fill in the tokens allowing to manage the spacings

### Dependencies 📦

No dependencies.

### Examples 🌈

- [nordhealth.design](https://nordhealth.design/tokens/#space)
- [Polaris Design system](https://polaris.shopify.com/tokens/shape) 

### Motivation 🔦

I need to be able to use spacings variables quickly, both in foundations and in a theme.

### New 🆕

- [x] Validated in a grooming session

### Backlog 📋

- [x] Has a good summary
- [x] Has example link(s)

### Design in progress 🏗

- [x] Analysis _(functional & technical)_
- [x] Design refinement
- [x] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
This topic has been launched in beta test.
However, its status in the board no longer reflects the current reality, so it has been moved to our "New" column.
We will keep you informed of the different advances.
Thank you.
