### ISSUE TITLE
DatePicker component

### ISSUE THREAD

**Issue by AlbertNambiaparambil** [Decathlon/vitamin-design#92]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Summary 💡

Hello team!
I am opening this request to push for the creation of a DatePicker component as it is becoming necessary for multiple teams.

There are some teams already working on a DatePicker component to permit selection of:

A specific date, &
A range of dates.
It would be interesting to unify these projects to have one component that serves both the purposes.
Attaching a link to the figma file (CSS codes included) that contains the DatePicker component of the affiliation website of Spain:

[Figma] https://www.figma.com/file/d5ce8AD12cTYbuhctBCSbK/A---Dashboard-Afiliado?node-id=208%3A1880
Albert Nambiaparambil (UXUI, Decathlon Spain)

--------
From @Aurelien Blareau

[Figma]https://www.figma.com/file/CpaqbCiA2MA6tGfslXzC40/%5BLib%5Dcomponents?node-id=0%3A1

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by lauthieb** [comment]
Will be tracked here: https://github.com/dktunited/vitamin-play/issues/45
