### ISSUE TITLE
Interactive states doesn't work well on mobile or Figma mirror app

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#94]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Current behavior 😯

Today for example on radio button nothing happen on mobile when tapping one.
(all figma lib concerned and all interactive components)

### Expected behavior 🤔

Tomorrow we have to be sure that when tapping radio on mobile it works :) For testing it's better.
(all figma lib concerned and all interactive components)

**Comment by Sabrinavigil** [comment]
No impact for dev library
