### ISSUE TITLE
[Bug]: Under size chart, 'inches' data/info is not visible even when toggled to inches

### ISSUE THREAD

**Issue by Ashika2409** [Decathlon/vitamin-design#95]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Vitamin Web UI Kit

### Current behavior 😯

when toggled between CM->INCHES under the size chart, the "Centimeter" data remains intact.
https://www.decathlon.in/p/8380664/jogging-clothing/women-s-long-sleeved-running-t-shirt-sun-protect-black?id=8380664&type=p

https://user-images.githubusercontent.com/67723981/193392245-cc15022c-874b-4340-b682-fb6a368745db.mp4

### Expected behavior 🤔

When the user toggles to "CM", the rendered size data should be of centimeter.
and when the measurement unit is toggled to "INCHES", the rendered data should be of Inches.

### Screenshots / Videos 📸

https://user-images.githubusercontent.com/67723981/193390918-f43cc302-19b1-4369-8364-3069d4aea4e1.mp4

![image](https://user-images.githubusercontent.com/67723981/193391904-874ad208-f668-4b6a-8659-91e51cd84c2a.png)
![2022-10-01_09h42_22](https://user-images.githubusercontent.com/67723981/193392047-22aa88f8-5d27-4caa-9d71-f7a534138201.png)

**Comment by Sabrinavigil** [comment]
Hello @Ashika2409 thank you for your feedback. This issue concerns the India e-commerce site and not the United Design System. Can you contact the teams directly?
