### ISSUE TITLE
[Icon]: New icon share-iOS

### ISSUE THREAD

**Issue by LoicVieira** [Decathlon/vitamin-design#96]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

share-ios

### Icon description

<img width="976" alt="image" src="https://user-images.githubusercontent.com/114481464/193591135-42d75f7d-a43a-448f-b202-3d1dd7427331.png">

Used to share content out of the app (with native share-bottom-layout).

### Icon keywords

share

### Icon author

Loïc Vieira

### Icon SVG code

```shell
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_6827_1497)">
<path d="M12 15.0104C12.4978 15.0104 12.8908 14.6125 12.8908 14.1453V5.55536L12.821 4.27509L13.3275 4.92388L14.4716 6.13495C14.6288 6.30796 14.8472 6.39446 15.0655 6.39446C15.4935 6.39446 15.8515 6.08305 15.8515 5.64187C15.8515 5.41696 15.7642 5.24394 15.607 5.08824L12.69 2.31142C12.4541 2.08651 12.2358 2 12 2C11.7642 2 11.5371 2.08651 11.31 2.31142L8.39301 5.08824C8.22707 5.24394 8.13974 5.41696 8.13974 5.64187C8.13974 6.08305 8.49782 6.39446 8.92576 6.39446C9.1441 6.39446 9.37118 6.30796 9.51965 6.13495L10.6725 4.92388L11.179 4.27509L11.1004 5.55536V14.1453C11.1004 14.6125 11.5022 15.0104 12 15.0104ZM6.9607 22H17.0393C18.9782 22 20 20.9879 20 19.0934V10.6678C20 8.77336 18.9782 7.76125 17.0393 7.76125H14.7249V9.69031H16.8734C17.6332 9.69031 18.0524 10.0796 18.0524 10.8668V18.8945C18.0524 19.6903 17.6332 20.0709 16.8734 20.0709H7.12664C6.35808 20.0709 5.9476 19.6903 5.9476 18.8945V10.8668C5.9476 10.0796 6.35808 9.69031 7.12664 9.69031H9.30131V7.76125H6.9607C5.03057 7.76125 4 8.77336 4 10.6678V19.0934C4 20.9965 5.03057 22 6.9607 22Z" fill="#001018"/>
</g>
<defs>
<clipPath id="clip0_6827_1497">
<rect width="24" height="24" fill="white"/>
</clipPath>
</defs>
</svg>
```

### Are there any other important details?

Share icon already exist in Vitamin for Android.
We need it for iOS.

We will have two share icon : we must keep and rename the old one to make the difference.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/114481464/193591920-3b8ea93c-3fdc-46d3-9658-a3b3a184e075.png">

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1280)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
