### ISSUE TITLE
[Icon]: New icon <line>

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-design#99]
### Duplicates ❌

- [X] I have searched the existing icons and requests.

### Icon name

Line

### Icon description

Line is a messaging application
[RemixIcon_SVG_2210111032.zip](https://github.com/Decathlon/vitamin-design/files/9753087/RemixIcon_SVG_2210111032.zip)

### Icon keywords

Messaging, application

### Icon author

Remix

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by sylvain-costanzo** [comment]
Can you add Kakaotalk and naver icon as well please.
Kakaotalk exist in remix icon, but naver doesn't
[RemixIcon_SVG_kakotalk.zip](https://github.com/Decathlon/vitamin-design/files/9753246/RemixIcon_SVG_kakotalk.zip)
![Naver_Logotype](https://user-images.githubusercontent.com/111066279/195043705-8f62af3c-b357-4c63-9c9b-073ccd4e272d.svg)

**Comment by Sabrinavigil** [comment]
Thanks for you message @sylvain-costanzo 
We added : 
line 
kakao-talk
naver

![Image](https://user-images.githubusercontent.com/65814825/196431344-77491ac2-d08c-4763-9d42-fc77a1d6424a.png)
![Image](https://user-images.githubusercontent.com/65814825/196431468-98df63d5-cc21-4388-9037-b7ff61b73dbd.png)

**Comment by lauthieb** [comment]
Thank you!

For your information, you can check the follow-up for development on each platform repository:
- [Web](https://github.com/Decathlon/vitamin-web/issues/1284)
- [Android](https://github.com/Decathlon/vitamin-android/issues/142)
- [iOS](https://github.com/Decathlon/vitamin-ios/issues/91)
- [Compose](https://github.com/Decathlon/vitamin-compose/issues/47)

Have a great day,
